// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: internal/infrastructure/plugin/proto/forward.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThirdPartyForwardDTU_Forward_FullMethodName = "/third_forward_dtu.v1.ThirdPartyForwardDTU/Forward"
	ThirdPartyForwardDTU_Answer_FullMethodName  = "/third_forward_dtu.v1.ThirdPartyForwardDTU/Answer"
)

// ThirdPartyForwardDTUClient is the client API for ThirdPartyForwardDTU service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThirdPartyForwardDTUClient interface {
	Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error)
}

type thirdPartyForwardDTUClient struct {
	cc grpc.ClientConnInterface
}

func NewThirdPartyForwardDTUClient(cc grpc.ClientConnInterface) ThirdPartyForwardDTUClient {
	return &thirdPartyForwardDTUClient{cc}
}

func (c *thirdPartyForwardDTUClient) Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ThirdPartyForwardDTU_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thirdPartyForwardDTUClient) Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerResponse)
	err := c.cc.Invoke(ctx, ThirdPartyForwardDTU_Answer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThirdPartyForwardDTUServer is the server API for ThirdPartyForwardDTU service.
// All implementations must embed UnimplementedThirdPartyForwardDTUServer
// for forward compatibility.
type ThirdPartyForwardDTUServer interface {
	Forward(context.Context, *ForwardRequest) (*emptypb.Empty, error)
	Answer(context.Context, *AnswerRequest) (*AnswerResponse, error)
	mustEmbedUnimplementedThirdPartyForwardDTUServer()
}

// UnimplementedThirdPartyForwardDTUServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThirdPartyForwardDTUServer struct{}

func (UnimplementedThirdPartyForwardDTUServer) Forward(context.Context, *ForwardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedThirdPartyForwardDTUServer) Answer(context.Context, *AnswerRequest) (*AnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedThirdPartyForwardDTUServer) mustEmbedUnimplementedThirdPartyForwardDTUServer() {}
func (UnimplementedThirdPartyForwardDTUServer) testEmbeddedByValue()                              {}

// UnsafeThirdPartyForwardDTUServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThirdPartyForwardDTUServer will
// result in compilation errors.
type UnsafeThirdPartyForwardDTUServer interface {
	mustEmbedUnimplementedThirdPartyForwardDTUServer()
}

func RegisterThirdPartyForwardDTUServer(s grpc.ServiceRegistrar, srv ThirdPartyForwardDTUServer) {
	// If the following call pancis, it indicates UnimplementedThirdPartyForwardDTUServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThirdPartyForwardDTU_ServiceDesc, srv)
}

func _ThirdPartyForwardDTU_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyForwardDTUServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyForwardDTU_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyForwardDTUServer).Forward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThirdPartyForwardDTU_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyForwardDTUServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyForwardDTU_Answer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyForwardDTUServer).Answer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThirdPartyForwardDTU_ServiceDesc is the grpc.ServiceDesc for ThirdPartyForwardDTU service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThirdPartyForwardDTU_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "third_forward_dtu.v1.ThirdPartyForwardDTU",
	HandlerType: (*ThirdPartyForwardDTUServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _ThirdPartyForwardDTU_Forward_Handler,
		},
		{
			MethodName: "Answer",
			Handler:    _ThirdPartyForwardDTU_Answer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/infrastructure/plugin/proto/forward.proto",
}
