// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: forward.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForwardService_Forward_FullMethodName = "/forward_server.v1.ForwardService/Forward"
	ForwardService_Answer_FullMethodName  = "/forward_server.v1.ForwardService/Answer"
)

// ForwardServiceClient is the client API for ForwardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForwardServiceClient interface {
	Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error)
}

type forwardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardServiceClient(cc grpc.ClientConnInterface) ForwardServiceClient {
	return &forwardServiceClient{cc}
}

func (c *forwardServiceClient) Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ForwardService_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardServiceClient) Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerResponse)
	err := c.cc.Invoke(ctx, ForwardService_Answer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardServiceServer is the server API for ForwardService service.
// All implementations must embed UnimplementedForwardServiceServer
// for forward compatibility.
type ForwardServiceServer interface {
	Forward(context.Context, *ForwardRequest) (*emptypb.Empty, error)
	Answer(context.Context, *AnswerRequest) (*AnswerResponse, error)
	mustEmbedUnimplementedForwardServiceServer()
}

// UnimplementedForwardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForwardServiceServer struct{}

func (UnimplementedForwardServiceServer) Forward(context.Context, *ForwardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedForwardServiceServer) Answer(context.Context, *AnswerRequest) (*AnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedForwardServiceServer) mustEmbedUnimplementedForwardServiceServer() {}
func (UnimplementedForwardServiceServer) testEmbeddedByValue()                        {}

// UnsafeForwardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwardServiceServer will
// result in compilation errors.
type UnsafeForwardServiceServer interface {
	mustEmbedUnimplementedForwardServiceServer()
}

func RegisterForwardServiceServer(s grpc.ServiceRegistrar, srv ForwardServiceServer) {
	// If the following call pancis, it indicates UnimplementedForwardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForwardService_ServiceDesc, srv)
}

func _ForwardService_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardServiceServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardService_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardServiceServer).Forward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardService_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardServiceServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardService_Answer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardServiceServer).Answer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForwardService_ServiceDesc is the grpc.ServiceDesc for ForwardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forward_server.v1.ForwardService",
	HandlerType: (*ForwardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _ForwardService_Forward_Handler,
		},
		{
			MethodName: "Answer",
			Handler:    _ForwardService_Answer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forward.proto",
}
